apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: selenium-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:12-alpine
          envFrom:
            - configMapRef:
                name: healenium-config
          ports:
            - containerPort: 5432
