"""
reporter.py — Generate JSON and Markdown collision reports.

Follows the vulnerability-aggregator/reporter.py pattern for
markdown generation.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone

from .analyzer import CollisionReport


def generate_json_report(report: CollisionReport) -> str:
    """Serialize CollisionReport to formatted JSON."""
    data = asdict(report)
    data["generated_at"] = datetime.now(timezone.utc).isoformat()
    return json.dumps(data, indent=2)


def generate_markdown_report(report: CollisionReport) -> str:
    """Generate a human-readable Markdown collision report."""
    lines: list[str] = []

    lines.append("# Branch Collision Report")
    lines.append("")
    lines.append(f"**Repository:** `{report.repo}`")
    lines.append(f"**Base branch:** `{report.base_branch}`")
    lines.append(f"**Branches analyzed:** {report.branches_analyzed}")
    lines.append(f"**Total files touched:** {report.total_files_touched}")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Risk summary
    risk_emoji = {
        "CRITICAL": "!!",
        "HIGH": "!",
        "MODERATE": "*",
        "LOW": "-",
    }
    marker = risk_emoji.get(report.overall_risk, "-")
    lines.append(f"## Overall Risk: {report.overall_risk} ({marker} score: {report.overall_score:.4f})")
    lines.append("")

    if not report.overlapping_files:
        lines.append("No file-level collisions detected across active branches.")
        return "\n".join(lines)

    # Overlapping files table
    lines.append(f"## File Collisions ({len(report.overlapping_files)} files)")
    lines.append("")
    lines.append("| File | Category | Branches | Lines Changed | Severity |")
    lines.append("|---|---|---|---|---|")

    for overlap in report.overlapping_files:
        branches_str = ", ".join(overlap.branches)
        lines.append(
            f"| `{overlap.path}` | {overlap.category} "
            f"| {branches_str} | {overlap.total_lines_changed} "
            f"| **{overlap.severity_score:.2f}** |"
        )

    lines.append("")

    # Category breakdown
    categories: dict[str, int] = {}
    for overlap in report.overlapping_files:
        categories[overlap.category] = categories.get(overlap.category, 0) + 1

    if categories:
        lines.append("## By Category")
        lines.append("")
        lines.append("| Category | Colliding Files |")
        lines.append("|---|---|")
        for cat in ["source", "config", "test", "ci", "docs"]:
            count = categories.get(cat, 0)
            if count > 0:
                lines.append(f"| {cat} | {count} |")
        lines.append("")

    # Semantic overlaps
    if report.semantic_overlaps:
        lines.append(f"## Semantic Conflicts ({len(report.semantic_overlaps)} analyzed)")
        lines.append("")
        lines.append("| File | Branch A | Branch B | Likelihood | Functions |")
        lines.append("|---|---|---|---|---|")

        for sem in report.semantic_overlaps:
            funcs = ", ".join(sem.functions_affected) if sem.functions_affected else "--"
            lines.append(
                f"| `{sem.file_path}` | {sem.branch_a} | {sem.branch_b} "
                f"| **{sem.conflict_likelihood}** | {funcs} |"
            )

        lines.append("")

        # Explanations
        high_sem = [s for s in report.semantic_overlaps if s.conflict_likelihood in ("high", "medium")]
        if high_sem:
            lines.append("### Conflict Details")
            lines.append("")
            for sem in high_sem:
                lines.append(f"**`{sem.file_path}`** ({sem.branch_a} vs {sem.branch_b}):")
                lines.append(f"> {sem.explanation}")
                lines.append("")

    lines.append("---")
    lines.append("*Generated by branch-collision-monitor*")
    lines.append("")

    return "\n".join(lines)
