"""Tests for comparison/reporter.py — JSON and Markdown report generation."""

import json

import pytest

from comparison.metrics import build_comparison_report
from comparison.reporter import generate_json_report, generate_markdown_report


class TestJsonReport:
    @pytest.mark.smoke
    def test_valid_json(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        json_str = generate_json_report(report)
        data = json.loads(json_str)
        assert "scenarios" in data
        assert "traditional_total_ms" in data
        assert "ai_driven_total_ms" in data

    def test_scenario_count(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        data = json.loads(generate_json_report(report))
        assert len(data["scenarios"]) == 8

    def test_speed_ratio_present(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        data = json.loads(generate_json_report(report))
        assert "speed_ratio" in data
        assert data["speed_ratio"] > 0


class TestMarkdownReport:
    @pytest.mark.smoke
    def test_contains_header(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        md = generate_markdown_report(report)
        assert "# Stagehand vs Playwright Comparison Report" in md

    def test_contains_summary_table(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        md = generate_markdown_report(report)
        assert "## Summary" in md
        assert "Total duration (ms)" in md
        assert "Speed ratio" in md

    def test_contains_scenario_results(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        md = generate_markdown_report(report)
        assert "## Scenario Results" in md
        assert "login" in md
        assert "inventory" in md
        assert "cart" in md
        assert "checkout" in md

    def test_contains_approach_labels(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        md = generate_markdown_report(report)
        assert "traditional" in md
        assert "ai-driven" in md

    def test_contains_footer(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        md = generate_markdown_report(report)
        assert "*Generated by stagehand-agent*" in md

    def test_contains_generated_timestamp(self, sample_scenario_results):
        report = build_comparison_report(sample_scenario_results)
        md = generate_markdown_report(report)
        assert "**Generated:**" in md
        assert "UTC" in md
