"""Generate compliance evidence reports in markdown and JSON."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from .mapper import ComplianceMap, group_by_clause


def generate_markdown(compliance_map: ComplianceMap) -> str:
    """Generate a markdown compliance evidence report."""
    lines: list[str] = []
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines.append("# QMS Evidence Collection Report")
    lines.append("")
    lines.append(f"**Generated:** {timestamp}")
    lines.append(f"**Unique clauses covered:** {compliance_map.unique_clause_count}")
    lines.append(f"**Total evidence files:** {compliance_map.total_evidence_files}")
    lines.append("")

    # Summary table
    lines.append("## Coverage Summary")
    lines.append("")
    lines.append("| Standard | Clauses Covered | Evidence Items |")
    lines.append("|----------|----------------|----------------|")

    iso_9001 = compliance_map.iso_9001_clauses
    soc2 = compliance_map.soc2_controls
    iso_17025 = compliance_map.iso_17025_clauses

    iso_9001_unique = len(set(e.clause_id for e in iso_9001))
    soc2_unique = len(set(e.clause_id for e in soc2))
    iso_17025_unique = len(set(e.clause_id for e in iso_17025))

    lines.append(f"| ISO 9001:2015 | {iso_9001_unique} | {len(iso_9001)} |")
    lines.append(f"| SOC 2 (CC-series) | {soc2_unique} | {len(soc2)} |")
    lines.append(f"| ISO/IEC 17025:2017 | {iso_17025_unique} | {len(iso_17025)} |")
    lines.append("")

    # Detailed breakdown by standard
    grouped = group_by_clause(compliance_map)

    for standard in ["ISO 9001:2015", "SOC 2", "ISO/IEC 17025:2017"]:
        clauses = grouped.get(standard, {})
        if not clauses:
            continue

        lines.append(f"## {standard}")
        lines.append("")

        for clause_id in sorted(clauses.keys()):
            evidence_list = clauses[clause_id]
            title = evidence_list[0].title
            lines.append(f"### {standard} {clause_id} — {title}")
            lines.append("")

            for ev in evidence_list:
                lines.append(f"**Artifact type:** `{ev.artifact_type}`")
                lines.append(f"**Rationale:** {ev.rationale}")
                lines.append(f"**Frameworks:** {', '.join(ev.frameworks)}")
                lines.append(f"**Evidence files ({len(ev.evidence_files)}):**")
                for f in ev.evidence_files[:5]:
                    lines.append(f"  - `{f}`")
                if len(ev.evidence_files) > 5:
                    lines.append(f"  - ... and {len(ev.evidence_files) - 5} more")
                lines.append("")

    # Compliance gap analysis
    lines.append("## Gap Analysis")
    lines.append("")
    lines.append("The following areas may require additional evidence for full audit readiness:")
    lines.append("")

    _gap_check(lines, iso_9001_unique, soc2_unique, iso_17025_unique)

    lines.append("---")
    lines.append("*Generated by qms-evidence-collector — qa-automation-portfolio*")

    return "\n".join(lines)


def _gap_check(
    lines: list[str],
    iso_9001_count: int,
    soc2_count: int,
    iso_17025_count: int,
) -> None:
    """Add gap analysis notes based on coverage counts."""
    if iso_9001_count < 10:
        lines.append(
            f"- ISO 9001: {iso_9001_count} clauses covered. "
            "Consider adding management review records (5.6), internal audit results (9.2), "
            "and customer feedback data (9.1.2) for broader coverage."
        )
    if soc2_count < 5:
        lines.append(
            f"- SOC 2: {soc2_count} controls covered. "
            "Consider adding access review logs (CC6.2), incident response runbooks (CC7.3), "
            "and vendor risk assessments (CC9.2)."
        )
    if iso_17025_count < 4:
        lines.append(
            f"- ISO/IEC 17025: {iso_17025_count} clauses covered. "
            "Consider adding measurement uncertainty budgets (7.6), "
            "proficiency testing records (7.7.2), and equipment calibration logs (6.4.1)."
        )
    if iso_9001_count >= 10 and soc2_count >= 5 and iso_17025_count >= 4:
        lines.append("- No critical gaps identified at this coverage level.")
    lines.append("")


def generate_json(compliance_map: ComplianceMap) -> dict:
    """Generate a JSON-serializable compliance evidence report."""
    timestamp = datetime.now(timezone.utc).isoformat()
    grouped = group_by_clause(compliance_map)

    report: dict = {
        "generated_at": timestamp,
        "summary": {
            "unique_clauses_covered": compliance_map.unique_clause_count,
            "total_evidence_files": compliance_map.total_evidence_files,
            "iso_9001_clauses": len(set(e.clause_id for e in compliance_map.iso_9001_clauses)),
            "soc2_controls": len(set(e.clause_id for e in compliance_map.soc2_controls)),
            "iso_17025_clauses": len(set(e.clause_id for e in compliance_map.iso_17025_clauses)),
        },
        "standards": {},
    }

    for standard, clauses in grouped.items():
        report["standards"][standard] = {}
        for clause_id, evidence_list in sorted(clauses.items()):
            report["standards"][standard][clause_id] = {
                "title": evidence_list[0].title,
                "evidence": [
                    {
                        "artifact_type": ev.artifact_type,
                        "rationale": ev.rationale,
                        "frameworks": ev.frameworks,
                        "file_count": len(ev.evidence_files),
                    }
                    for ev in evidence_list
                ],
            }

    return report


def write_report(compliance_map: ComplianceMap, output_path: str, fmt: str = "markdown") -> None:
    """Write the compliance report to a file.

    Args:
        compliance_map: Mapped compliance evidence.
        output_path: Destination file path.
        fmt: "markdown" or "json".
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if fmt == "json":
        report = generate_json(compliance_map)
        path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    else:
        markdown = generate_markdown(compliance_map)
        path.write_text(markdown, encoding="utf-8")
