"""
reporter.py — Generate JSON and Markdown comparison reports.

Follows the branch-collision-monitor/monitor/reporter.py pattern for
structured report generation.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone

from comparison.metrics import ComparisonReport


def generate_json_report(report: ComparisonReport) -> str:
    """Serialize ComparisonReport to formatted JSON."""
    data = asdict(report)
    return json.dumps(data, indent=2)


def generate_markdown_report(report: ComparisonReport) -> str:
    """Generate a human-readable Markdown comparison report."""
    lines: list[str] = []

    lines.append("# Stagehand vs Playwright Comparison Report")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Scenarios:** {len(report.scenarios)}")
    lines.append(f"**All passed:** {'Yes' if report.all_passed else 'No'}")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Traditional | AI-Driven |")
    lines.append("|---|---|---|")
    lines.append(
        f"| Total duration (ms) | {report.traditional_total_ms:.1f} "
        f"| {report.ai_driven_total_ms:.1f} |"
    )
    lines.append(f"| Total tokens | 0 | {report.ai_total_tokens} |")
    lines.append(f"| Speed ratio (AI / Traditional) | — | {report.speed_ratio}x |")
    lines.append("")

    # Per-scenario results
    traditional = [s for s in report.scenarios if s.approach == "traditional"]
    ai_driven = [s for s in report.scenarios if s.approach == "ai-driven"]

    if traditional or ai_driven:
        lines.append("## Scenario Results")
        lines.append("")
        lines.append("| Scenario | Approach | Passed | Duration (ms) | Tokens | Error |")
        lines.append("|---|---|---|---|---|---|")

        for result in report.scenarios:
            status = "PASS" if result.passed else "FAIL"
            error_str = result.error or "—"
            lines.append(
                f"| {result.scenario} | {result.approach} | {status} "
                f"| {result.duration_ms:.1f} | {result.tokens_used} "
                f"| {error_str} |"
            )

        lines.append("")

    lines.append("---")
    lines.append("*Generated by stagehand-agent*")
    lines.append("")

    return "\n".join(lines)
