apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlm-backend
  namespace: selenium-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlm-backend
  template:
    metadata:
      labels:
        app: hlm-backend
    spec:
      containers:
        - name: hlm-backend
          image: healenium/hlm-backend:3.3.0
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: healenium-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: healenium-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: healenium-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healenium-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 7878
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
