apiVersion: v1
kind: Service
metadata:
  name: hlm-selector-imitator
  namespace: selenium-grid
spec:
  selector:
    app: hlm-selector-imitator
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
