"""
test_pact_provider.py — Pact provider verification.

Verifies that the FastAPI service satisfies all consumer contracts
defined in pact-consumer/pacts/.

Runs the real FastAPI app via TestClient on a local port, then
points the Pact verifier at the generated pact JSON files.
"""

import multiprocessing
import time
from pathlib import Path

import pytest
import uvicorn
from pact import Verifier

# Path to pact files generated by the consumer
PACT_DIR = Path(__file__).resolve().parent.parent.parent / "pact-consumer" / "pacts"
PROVIDER_URL = "http://localhost:8002"


def _run_server():
    """Start the FastAPI app on port 8002 for provider verification."""
    uvicorn.run("app.main:app", host="0.0.0.0", port=8002, log_level="warning")


@pytest.fixture(scope="module")
def provider_server():
    """Launch the FastAPI server in a subprocess for the duration of the test module."""
    proc = multiprocessing.Process(target=_run_server, daemon=True)
    proc.start()

    # Wait for the server to be ready
    import requests

    for _ in range(30):
        try:
            resp = requests.get(f"{PROVIDER_URL}/health", timeout=1)
            if resp.status_code == 200:
                break
        except requests.ConnectionError:
            pass
        time.sleep(0.5)
    else:
        proc.terminate()
        pytest.fail("FastAPI server did not start within 15 seconds")

    yield proc

    proc.terminate()
    proc.join(timeout=5)


@pytest.mark.skipif(
    not PACT_DIR.exists() or not list(PACT_DIR.glob("*.json")),
    reason="No pact files found. Run 'cd pact-consumer && npm test' first.",
)
def test_provider_satisfies_pact(provider_server):
    """Verify the FastAPI provider against all consumer pact files."""
    verifier = (
        Verifier("fastapi-service")
        .add_transport(url=PROVIDER_URL)
        .add_source(str(PACT_DIR))
    )
    verifier.verify()
